setwd("C:/Users/Ythie/Documents/Data Science/Exploratory Data Analysis")
c <- read.table('household_power_consumption.txt',skip=66637,nrows=2880,sep = ';')
a <- strptime(paste(c$V1,c$V2),'%d/%m/%Y %H:%M:%S')
par(mfrow = c(2,2))
plot(a,c$V3,type = 'l',xlab = 'datetime',ylab = 'Global Active Power (kilowatts)',cex.lab=0.5)
plot(a,c$V5,type = 'l',xlab = 'datetime',ylab = 'Voltage',cex.lab=0.5)
plot(a,c$V7,type = 'l',xlab = 'datetime',ylab = 'Energy sub metering',cex.lab=0.5)
lines(a,c$V8,col='red')
lines(a,c$V9,col='blue')
legend('topright',pch = '-',col = c('black','red','blue'),pt.cex=1,cex=0.25,legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'))
plot(a,c$V4,type = 'l',xlab = 'datetime',ylab = 'Global Reactive Power (kilowatts)',cex.lab=0.5)
dev.copy(png,'plot4.png',width=480,height=480)
dev.off()