setwd("C:/Users/Ythie/Documents/Data Science/Exploratory Data Analysis")
c <- read.table('household_power_consumption.txt',skip=66637,nrows=2880,sep = ';')
a <- strptime(paste(c$V1,c$V2),'%d/%m/%Y %H:%M:%S')
plot(a,c$V7,type = 'l',xlab = 'datetime',ylab = 'Energy sub metering')
lines(a,c$V8,col='red')
lines(a,c$V9,col='blue')
legend('topright',pch = '-',col = c('black','red','blue'),pt.cex = 1,cex = 0.5,legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'))
dev.copy(png,'plot3.png',width=480,height=480)
dev.off()